# theme: jekyll-theme-hacker
# title: Learn Learn Learn!!!
# description: Learning make happy!
# permalink: /404.html
# /cmd/xx.html
# permalink: /cmd/linux.html
# permalink: /cmd/docker.html
# permalink: /cmd/tmux.html
title:       Type
email:       ''
description: ''
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://type-jekyll.aspirethemes.com/' # The base hostname & protocol for your site
twitter:     ''
github:      ''
instagram:   ''
facebook:    ''

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

